peridot-php/peridot

- specs/application.spec.php
- src/Console/Application.php
- src/Runner/Runner.php
- src/Runner/RunnerInterface.php
This PR opens up getters and setters for `Configuration` and `Runner` in the `Application` class.
In addition, it opens up a getter for the `Environment` of the peridot application.
The `peridot.configure` event has been extended to pass a second argument to listeners that is the `Application` instance itself. This allows a listener to override the Runner used.
`RunnerInterface` introduced to allow implementations to be written against it.
> allow configuration of application Runner

- src/Core/TestResult.php
- src/Reporter/AbstractBaseReporter.php
Exception type hinting is pretty limiting in a couple of places. All we really need is an "Exception like" interface, but PHP does not provide such a thing, but it does allow us to remove type hints!
It has only been removed where it makes sense - such as outputting an error and the error object being emitted as part of test failure.
This basically creates an implicit contract that if your object has the same methods as an Exception, you should be golden - not to mention that it will still be mostly exceptions used.
My use case for this is hydrating exceptions out of serialized contexts in the peridot-concurrency plugin.
> remove exception type hints

- specs/command.spec.php
- src/Console/Command.php
Fixes #121 
Please note the intended 2.0 goal mentioned by #120 - once runner initialization is added to the command, we can have a default runner result of `Peridot\Runner\Runner`, similar to how the default loader mechanism works in the command.
> add runner accessors to Command

- peridot.php
Excluding hhvm code coverage as the difference between hhvm code coverage and xdebug seems to be too great.
See https://github.com/facebook/hhvm/issues/1589
> exclude hhvm from coverage

- specs/context.spec.php
- specs/suite.spec.php
- specs/suiteloader.spec.php
- specs/test.spec.php
- src/Core/AbstractTest.php
- src/Runner/Context.php
- src/Runner/SuiteLoader.php
It would generally be useful to have the file path available on test objects - for information/reporting purposes.
This PR updates the context with a file path based on what file is being loaded. All suites or tests included will receive file information from the context when created by it.
Fixes #124
> Set test path on test objects

- specs/runner.spec.php
- src/Reporter/AbstractBaseReporter.php
- src/Runner/Runner.php
It makes sense that the runner should supply how long it took to do its thing. This passes an end time as a float, so PHP_Timer static calls are avoided.
Fixes #129
> runner.end now supplies run time as float

- specs/test-result.spec.php
- src/Core/TestResult.php
Adding accessors to a few properties of this key model :)
It seemed appropriate to have setters available for this model. My use case came up in the concurrency plugin when trying to get an appropriate exit code. We currently set the exit code like this in `Command`:
```php
$result = new TestResult($this->eventEmitter);
$this->getLoader()->load($this->configuration->getPath());
$this->factory->create($this->configuration->getReporter());
$this->runner->run($result);
if ($result->getFailureCount() > 0) {
return 1;
}
return 0;
```
This works for normal test results, but what about a different condition for a failure? This is the case in the concurrency plugin when a file loaded in a worker process contains PHP fatal errors. Since we can recover from those in a concurrent context, there is …
> include accessors to test result counts

- specs/abstract-base-reporter.spec.php
- specs/context.spec.php
- specs/suite.spec.php
- specs/test.spec.php
- src/Console/Environment.php
- src/Core/AbstractTest.php
- src/Core/Suite.php
- src/Core/Test.php
- src/Core/TestInterface.php
- src/Reporter/AbstractBaseReporter.php
- src/Runner/Context.php
`TestInterface` supports setting arguments to be called with test definitions via `getDefinitionArguments` and `setDefinitionArguments`. This should be useful for passing arguments to test or suite definitions via plugins.
Since suites generally execute early to build test trees, a new `suite.define` event has been added, and listeners receive the suite that has just been defined. This event is where to hook in for setting suite definition arguments.
For instances of `Test` - the classic `test.run` event can be used for the same purpose.
Fixes #134
> Support definition arguments

- peridot.php
- specs/configuration.spec.php
- specs/context.spec.php
- specs/suiteloader.spec.php
- src/Configuration.php
- src/Console/Application.php
- src/Console/Environment.php
- src/Core/Context.php
- src/Dsl.php
- src/Reporter/SpecReporter.php
- src/Runner/SuiteLoader.php
The new default spec directory is `specs/` instead of the current working directory. This PR also adds Context into the Core namespace.
Fixes #130 and Fixes #145
> Default specs directory and move Context into Core

- src/Console/Command.php
This arg was recently added by Symfony because they don't understand SemVer. Since this optional argument is missing in Peridot's extending class, PHP throws a Strict Standards error.
> Added optional arg to Console\Command::getSynopsis

- specs/configuration.spec.php
- src/Configuration.php
- src/Console/ConfigurationReader.php
- src/Console/InputDefinition.php
- src/Reporter/AbstractBaseReporter.php
PR regarding #165 
The `-f` shortcut may not imply this option intuitively, but both `C` and `c` has been taken.
I have tested with apache with backtick operators and it works, but I have no way to emulate `->hasTty() === false` environment when tests are run from CLI.
I just quickly pimped it up, would def. like your comments.
> Add --force-color option

- specs/application.spec.php
- specs/test-result.spec.php
The `application.spec.php` spec is throwing a fatal error in PHP 7 because the test fails to pass an input interface to the method.
This PR addresses that issue.
> spec should use getCommandName interface correctly

- README.md
The Box project website (http://box-project.org) seems to have expired and been taken over by a domain squatter / auction service.  The README could use the Github project URL instead.
> Update Box project link to working URL.

- src/Core/Suite.php
This PR is very simple, it allows `Suite::runTest()` to run any `TestInterface` implementation, instead of requiring tests to extend `AbstractTest`. It seems like the use of `AbstractTest` as a type hint was probably left over from a time before `TestInterface` existed.
What's more interesting, and what I can't figure out, is why this was **only** causing problems for me under PHP 7.
I have a pretty advanced use case. I am testing asynchronous code that uses [Recoil](https://github.com/recoilphp/recoil), a generator-based coroutine library. I'm using Peridot's event system to wrap every test in my own implementation of `TestInterface` that runs the test under Recoil. My Peridot configuration looks like this:
```php
// ... snip ...
class AsyncTestWrapper implements TestInterface
{
public …
```
> Changed test typehint from AbstractTest to TestInterface.

- specs/runner.spec.php
- src/Runner/Runner.php
I use [Asplode](https://github.com/eloquent/asplode) in my `peridot.php` to set up an error handler that converts errors into error exceptions. I only recently realised that this was not working, and that my tests were passing silently despite errors.
I see two problems here:
1. Peridot is currently overwriting and ignoring any existing error handler.
2. Peridot is currently silencing errors, because the error handler doesn't actually do anything except to raise a Peridot "error" event. That seems like a dangerous choice. Shouldn't a test fail if an error occurs during its execution, and shouldn't that happen without having to write a custom "error" event handler?
This PR addresses these two problems in the following ways:
1. If there is an existing error handler, Peridot will now …
> Do not suppress errors

- .scrutinizer.yml
- composer.json
- fixtures/error-polyfill.php
- specs/runner.spec.php
- specs/spec-reporter.spec.php
- specs/test.spec.php
- src/Core/Test.php
- src/Runner/Runner.php
Continuing from #175, this PR further improves the error handling in Peridot.
The biggest change is that when an error occurs in a test, that test will now fail. This new behavior will honor the `error_reporting` setting, meaning that systems that typically ignore errors of a given severity can still be tested under Peridot. This is the same underlying mechanism used by the error control operator (`@`), so that will also work as intended.
Regardless of the `error_reporting` level, a Peridot `error` event will still be emitted. It will be up to individual listener implementations to decide whether to honor the `error_reporting` level.
Another change is to the behavior of tests in which multiple failures occur. Previously, if a test failed AND its teardown also failed, the teardown failure …
> Tests now fail when an error occurs.

- fixtures/focused.spec.php
- specs/context.spec.php
- specs/suite.spec.php
- specs/suiteloader.spec.php
- specs/test.spec.php
- src/Core/AbstractTest.php
- src/Core/Suite.php
- src/Core/Test.php
- src/Core/TestInterface.php
- src/Dsl.php
- src/Runner/Context.php
- src/Test/ItWasRun.php
This is a work in progress, to implement #185
> [WIP] Focused tests

- .travis.yml
- Makefile
- README.md
- composer.json
- peridot.php
Switches us over to using codecov
@ezzatron - I took a cue from you and introduced a Makefile. codecov says it aggregates reports across builds, so I thought it would be good to let code coverage run for all build targets in the matrix (with the exception of allowed failures)
The Makefile currently only defines a `coverage` target, but we can define more for other build tasks as we need them. 
The `coverage` target is conditionally defined to skip nightly builds and to use `phpdbg` for PHP 7.0 and 7.1 (as it is the only driver supported for those versions with our version of `phpunit/php-code-coverage`)
> Adds codecov support and updates build matrix

- .gitignore
- composer.json
- composer.lock
This PR does a few related things:
- Adds the `composer.lock` file. This is [recommended by Composer](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file), and should improve build times, and help when switching branches with different dependencies.
- Cleans up the `.gitignore` file, removing the `composer.lock` entry, and a bunch of entries that should really be in a [global .gitignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore), such as `.DS_Store` and `.idea`.
- Uses slash prefixes in `.gitignore` where appropriate.
- Updates `composer.json` to use the [platform](https://getcomposer.org/doc/06-config.md#platform) config option, so that dependencies get locked at appropriate versions for our minimum PHP constraint.
- Updated …
> Commit the composer.lock file

- specs/configuration-reader.spec.php
- specs/configuration.spec.php
- specs/runner.spec.php
- specs/suite.spec.php
- src/Configuration.php
- src/Console/ConfigurationReader.php
- src/Console/InputDefinition.php
- src/Core/AbstractTest.php
- src/Core/Suite.php
- src/Core/TestInterface.php
- src/Runner/Runner.php
@brianium Here's a working prototype of the `--focus` and `--skip` CLI options.
In its current form, it works like Ginkgo, in that if you specify either option on the command line, it completely overrides any tests that are focused "programatically" with an `f` prefix. Seems like the approach that will cause the least confusion.
Definitely not perfect, and no tests yet, but hopefully it's a starting point for discussion :)
> [WIP] Implement --focus and --skip CLI options

- fixtures/focused.spec.php
- specs/configuration-reader.spec.php
- specs/configuration.spec.php
- specs/context.spec.php
- specs/runner.spec.php
- specs/suite.spec.php
- specs/suiteloader.spec.php
- specs/test.spec.php
- src/Configuration.php
- src/Console/ConfigurationReader.php
- src/Console/InputDefinition.php
- src/Core/AbstractTest.php
- src/Core/Suite.php
- src/Core/Test.php
- src/Core/TestInterface.php
- src/Dsl.php
- src/Runner/Context.php
- src/Runner/Runner.php
- src/Test/ItWasRun.php
> Focused specs

- fixtures/exception-trimming.spec.php
- specs/assert-exception.spec.php
- specs/spec-reporter.spec.php
- specs/suiteloader.spec.php
- src/AssertException.php
- src/Dsl.php
- src/Reporter/AbstractBaseReporter.php
This PR:
- Tidies up stack trace output by trimming stack entries that are irrelevant to the user.
- Adds the exception file and line number to the output, which was previously missing.
- Improves the exceptions thrown by failing `assert()` calls, by setting their file and line number to the location of the `assert()` call, rather than the location of the `ASSERT_CALLBACK` handler `throw` statement.
Closes #170.
> Improved stack trace output

- CHANGELOG.md
- specs/command.spec.php
- specs/runner.spec.php
- specs/spec-reporter.spec.php
- specs/test-result.spec.php
- src/Console/Command.php
- src/Core/TestResult.php
- src/Reporter/AbstractBaseReporter.php
- src/Reporter/SpecReporter.php
- src/Runner/Runner.php
This PR implements a similar feature to this one from Ginkgo:
> When Ginkgo detects that a passing test suite has a programmatically focused test it causes the suite to exit with a non-zero status code. This is to help detect erroneously committed focused tests on CI systems. When passed a command-line focus/skip flag Ginkgo exits with status code 0 - if you want to focus tests on your CI system you should explicitly pass in a -focus or -skip flag.
> When tests are focused via DSL, exit with a non-zero code.

- CHANGELOG.md
- specs/command.spec.php
- specs/composite-reporter.spec.php
- specs/configuration.spec.php
- specs/reporter-factory.spec.php
- src/Configuration.php
- src/Console/Command.php
- src/Console/InputDefinition.php
- src/Reporter/CompositeReporter.php
- src/Reporter/ReporterFactory.php
This PR adds support for multiple reporters.
Summary/justification of changes:
- This is a not a BC break, unless you count setting the default value of the `reporter` command-line option in `peridot.php`.
- Multiple reporters can now be specified on the command line with multiple `--reporter` options.
- The docs will need a minor update to reflect this.
- When multiple reporters are specified, they are composed into a 'composite' reporter.
- The first reporter gets the "real" output interface, and subsequent reporters get a buffered output interface. Once the `runner.end` event fires, any buffered output is displayed after the primary reporter's output, separated by a single newline. This prevents interlaced output, while retaining streaming output for the primary reporter.
- Retains …
> [WIP] Support for multiple reporters

- src/Dsl.php
This adds the `test` alias for `it` and the other variants. This is similar to facebook's Jest. I think there are some cases where `test` can be more suiting fo the test description.
Specifically, I've created a [package](https://github.com/krakphp/peridocs) which generates markdown documentation from your specs, and I've found that using `it` can make the wording weird, but `test` is more natural.
Btw, thank you so much for making this package, it's such a great tool!
Signed-off-by: RJ Garcia <rj@bighead.net>
> Add `test` alias for `it`

- composer.json
- composer.lock
- specs/configuration.spec.php
- specs/spec-reporter.spec.php
- src/Reporter/AbstractBaseReporter.php
Hey there!
Since I'm a big fan of testing with peridot, I can't help but notice there weren't that many updates as of late. I need Symfony Console >v4 in some of my projects, but can't, since Peridot still requires the v2.  
Hence I'd like to propose updating all dependencies to more recent versions, as well as raising the PHP version requirement to >= 7.1. 
I know, that shuns backwards compatibility. However, the definite EOL of PHP 5.6 is just ahead (Dec. 31st I think), so I'd say it's definitely okay to cut loose ends, too. Maybe in the shape of a new major version?
Let me know what you think.
*Forgot to mention it - I ran the full test suite, which is all green with some minor modifications.*
> Updated dependencies, PHP>=7.1
